<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <WindowsPackageType>MSIX</WindowsPackageType>
    <GenerateAppxPackageOnBuild>true</GenerateAppxPackageOnBuild>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <ApplicationIcon>favicon.ico</ApplicationIcon>
    <PackageCertificateThumbprint>3E936FDB371D50055C6B216D4FF7FA56A31564B7</PackageCertificateThumbprint>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.*" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.*" />
    <Content Include="favicon.ico" />
    <Content Include="StoreLogo.png" />
    <Content Include="Square150x150Logo.png" />
    <Content Include="Square44x44Logo.png" />
    <Content Include="Wide310x150Logo.png" />
  </ItemGroup>
</Project>
